### PR TITLE
styled components

### LINKED ISSUE #4: Convert to Styled Components
https://www.styled-components.com/docs/basics

Currently the code is structured very similarly to this so it should be an easy refactor!

### PR DESCRIPTION
**Pull request by robbawebba**
I've converted all of the styled tags below to use the styled-components library. All of the components are defined in `styledComponents.js` and imported into `App.js`.  

The only component I couldn't figure out right now is the buttons inside the app. They use tons of css classes and nested classes that make it tricky to convert. @michaelghinrichs Would you know how to solve this problem? If so, I'd be happy to pair with you or continue working on this PR. Thanks!
 
closes #4

### CODE REVIEW

**Review by karismatic-megafauna — APPROVED** [review]
Awesome! Nice work :)

**Comment by karismatic-megafauna** [comment]
and about the buttons, I agree, but that can come later! more than happy to pair on it!

**Comment by robbawebba** [comment]
@michaelghinrichs I just fixed some more merge conflicts to this branch so it's ready to be merged. If you think it's ready, you should merge this before it gets too stale and there are too many merge conflicts to handle.

**Comment by karismatic-megafauna** [comment]
Absolutely agree!

🚀  here we goooooooo!!! 🚀 

Thanks for the work on this!

Will make a followup issue and assign it to you for the buttons :)

**Comment by robbawebba** [comment]
Awesome, thanks!

**Pull request merged**
